version: '3.2'


services:


  mongodb:

    image: mongo

    ports:
      - 27017:27017

    environment:
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_ROOT_PASSWORD}

    volumes:
      - mongo-data:/data/db


  mongo-express:

    image: mongo-express

    ports:
      - 8081:8081

    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME:${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD:${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb

    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local